drycleaners/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.contrib.auth import views as auth_views

from . import views

app_name = 'drycleaners'

patterns = [
    
	# # # DEFAULT
    
	url(r'^$', views.invoices.index, name='index'),

    # # # INVOICES

    url(r'^invoice/new/$', views.invoices.new_invoice, name='new_invoice'),
    url(r'^invoice/all/$', views.invoices.all_invoices, name='all_invoices'),
    url(r'^invoice/draft/$', views.invoices.draft_invoices, name='draft_invoices'),
    url(r'^invoice/paid/$', views.invoices.paid_invoices, name='paid_invoices'),
    url(r'^invoice/unpaid/$', views.invoices.unpaid_invoices, name='unpaid_invoices'),
    url(r'^invoice/(?P<invoice_id>[0-9]+)/$', views.invoices.invoice, name='invoice'),
    url(r'^invoice/search/$', views.invoices.search_invoice, name='search_invoice'),
    url(r'^invoice/(?P<invoice_id>[0-9]+)/update/$', views.invoices.update_invoice, name='update_invoice'),
    url(r'^invoice/(?P<invoice_id>[0-9]+)/print/$', views.invoices.print_invoice, name='print_invoice'),
    url(r'^invoice/(?P<invoice_id>[0-9]+)/delete/$', views.invoices.delete_invoice, name='delete_invoice'),

    # # # ITEMS

    url(r'^invoice/(?P<invoice_id>[0-9]+)/item/add/$', views.items.add_item, name='add_item'),
    url(r'^invoice/(?P<invoice_id>[0-9]+)/item/(?P<invoiceitem_id>[0-9]+)/delete/$', views.items.delete_item, name='delete_item'),

    # # # INVOICE EXPENSES

    url(r'^invoice/(?P<invoice_id>[0-9]+)/expenses/add/$', views.expenses.add_invoice_expense, name='add_invoice_expense'),
    url(r'^invoice/(?P<invoice_id>[0-9]+)/expenses/(?P<expense_id>[0-9]+)/delete/$', views.expenses.delete_invoice_expense, name='delete_invoice_expense'),

    # # # BUSINESS EXPENSES
	
    url(r'^expenses/$', views.expenses.expense_list, name='expense_list'),
    url(r'^expenses/new/$', views.expenses.new_business_expense, name='new_business_expense'),
    url(r'^expenses/(?P<expense_id>[0-9]+)/delete/$', views.expenses.delete_business_expense, name='delete_business_expense'),

    # # # REPORTS

    url(r'^accounting/$', views.reports.accounting, name='accounting'),

    # # # ATTACHMENTS

    url(r'^invoice/(?P<invoice_id>[0-9]+)/attachments/add/$', views.invoices.upload_invoice_attachment, name='upload_invoice_attachment'),
    url(r'^invoice/(?P<invoice_id>[0-9]+)/attachments/(?P<invoiceattachment_id>[0-9]+)/delete/$', views.invoices.delete_invoice_attachment, name='delete_invoice_attachment'),
    url(r'^expenses/(?P<expense_id>[0-9]+)/attachments/add/$', views.expenses.upload_business_expense_attachment, name='upload_business_expense_attachment'),

    # # # CUSTOMERS

    url(r'^customers/$', views.customers.customer_list, name='customer_list'),
    url(r'^customer/(?P<customer_id>[0-9]+)/$', views.customers.customer, name='customer'),
	url(r'^customer/(?P<customer_id>[0-9]+)/update/$', views.customers.update_customer, name='update_customer'),
    url(r'^customer/(?P<customer_id>[0-9]+)/delete/$', views.customers.delete_customer, name='delete_customer'),
    url(r'^customer/new/$', views.customers.new_customer, name='new_customer'),

    # # # USER AUTHENTICATION
	
    url(r'^login/$', views.userauth.login_view, name='login'),
    url(r'^logout/$', views.userauth.logout_view, name='logout'),

    # # # ADMIN
	
    url(r'^users/$', views.admin.users, name='users'),
    url(r'^settings/$', views.admin.settings, name='settings'),
]

urlpatterns = [
    url(r'^', include(patterns, namespace="drycleaners")),
]

drycleaners/models.py
from __future__ import unicode_literals

from django.core.files.storage import FileSystemStorage
from django.db import models

# Create your models here.
class Customer(models.Model):
	name = models.CharField(max_length=256)
	address1 = models.CharField(max_length=256, blank=True)
	address2 = models.CharField(max_length=256, blank=True)
	city = models.CharField(max_length=128, blank=True)
	state = models.CharField(max_length=2, blank=True)
	zip = models.CharField(max_length=12, blank=True)
	email = models.CharField(max_length=256, blank=True)

	def __str__(self):
		return self.name
	
	def invoices(self):
		return Invoice.objects.filter(customer=self).count()

class Invoice(models.Model):
	customer = models.ForeignKey(Customer, on_delete=models.CASCADE)
	date = models.DateField()
	status = models.CharField(max_length=10)

	def __str__(self):
	    return str(self.id)

	def total_items(self):
		self.total = 0
		items = self.invoiceitem_set.all()

		for item in items:
			self.total += item.cost * item.qty

		return self.total

        def net(self):
		net = 0
                total = 0
		items = self.invoiceitem_set.all()
                for item in items:
			total += item.cost * item.qty
               
                for item in items:
			net = float(total) / float(1.20)

                return float("{0:.2f}".format(net))

        def gross(self):
		gross = 0
		items = self.invoiceitem_set.all()

		for item in items:
			gross = self.total

		return gross

	def vat(self):
	 	vat = 0
                net = 0
                total = 0
		items = self.invoiceitem_set.all()
                for item in items:
			total += item.cost * item.qty
               
                for item in items:
			net = float(total) / float(1.20)
               
               	for item in items:
			vat =  float(total) - float("{0:.2f}".format(net))

		return vat

	def total_expenses(self):
		total = 0
		expenses = self.expense_set.all()

		for expense in expenses:
			total += expense.cost * expense.qty

		return total

	def total(self):
		items = self.total_items()
		expenses = self.total_expenses()

		return items - expenses
		
	def paid(self):
		return self.status == 'Paid'
		
	def unpaid(self):
		return self.status == 'Unpaid'
		
	def draft(self):
		return self.status == 'Draft'

class InvoiceItem(models.Model):
	invoice = models.ForeignKey(Invoice, on_delete=models.CASCADE)
	name = models.CharField(max_length=128)
	description = models.TextField()
	cost = models.DecimalField(decimal_places=2, max_digits=10)
	qty = models.IntegerField()

	def total(self):
		return self.cost * self.qty

class Expense(models.Model):
	description = models.TextField()
	cost = models.DecimalField(decimal_places=2, max_digits=10)
	qty = models.IntegerField()
	invoice = models.ForeignKey(Invoice, on_delete=models.CASCADE, blank=True, null=True)
	date = models.DateField(blank=True, null=True)
		
	def total(self):
		return self.cost * self.qty

	def is_business_expense(self):
		return self.invoice is None

class InvoiceAttachment(models.Model):
	file = models.FileField(upload_to='invoice/')
	displayname = models.CharField(max_length=128)
	invoice = models.ForeignKey(Invoice, on_delete=models.CASCADE)

class ExpenseAttachment(models.Model):
	file = models.FileField(upload_to='expense/')
	displayname = models.CharField(max_length=128)
	expense = models.ForeignKey(Expense, on_delete=models.CASCADE)

drycleaners/views/admin.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.core.files.storage import FileSystemStorage
from django.contrib.auth.decorators import login_required
import datetime

from drycleaners.models import Customer, Invoice, InvoiceItem, Expense, InvoiceAttachment, ExpenseAttachment	



# Administrative settings
def users(request):
    return None


def settings(request):
    return None

drycleaners/views/customers.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.contrib.auth.decorators import login_required
import datetime

from drycleaners.models import Customer, Invoice, InvoiceItem, Expense, InvoiceAttachment, ExpenseAttachment



# List all customers
@login_required(login_url='login/')
def customer_list(request):
	customers = Customer.objects.all()
	context = {
		'title' : 'Customer List',
		'customers' : customers,
	}
	return render(request, 'customers.html', context)
	
	
	
# Show specific customer details
@login_required(login_url='login/')
def customer(request, customer_id):
	customer = get_object_or_404(Customer, pk=customer_id)
	invoices = Invoice.objects.filter(customer = customer)
	context = {
		'title' : "Customer info - %s" % customer.name,
		'customer' : customer,
		'invoices' : invoices,
	}
	return render(request, 'customer.html', context)

	
	
# Add new customer
@login_required(login_url='login/')
def new_customer(request):
	if request.method == 'POST':
		# Stuff from form
		c = Customer(name=request.POST['name'], address1=request.POST['address1'], address2=request.POST['address2'], city=request.POST['city'], state=request.POST['state'], zip=request.POST['zip'], email=request.POST['email'])
		c.save()
		
		if 'savecreate' in request.POST:
			i = Invoice(customer=c, date=datetime.date.today(), status='Unpaid')
			i.save()
			return HttpResponseRedirect(reverse('drycleaners:invoice', args=(i.id,)))
		else:
			return HttpResponseRedirect(reverse('drycleaners:customer_list'))
	else:
		return render(request, 'new_customer.html')



# Update customer
@login_required(login_url='login/')
def update_customer(request, customer_id):
	# Stuff from form
	c = get_object_or_404(Customer, pk=customer_id)
	
	c.name = request.POST['name']
	c.address1 = request.POST['address1']
	c.address2 = request.POST['address2']
	c.city = request.POST['city']
	c.state = request.POST['state']
	c.zip = request.POST['zip']
	c.email = request.POST['email']
	
	c.save()
	
	return HttpResponseRedirect(reverse('drycleaners:customer', args=(c.id,)))

		
# Delete customer
@login_required(login_url='login/')
def delete_customer(request, customer_id):
	customer = get_object_or_404(Customer, pk=customer_id)
	customer.delete()
	return HttpResponseRedirect(reverse('drycleaners:customer_list'))

drycleaners/views/expenses.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.core.files.storage import FileSystemStorage
from django.contrib.auth.decorators import login_required
import datetime

from drycleaners.models import Customer, Invoice, InvoiceItem, Expense, InvoiceAttachment, ExpenseAttachment



# Add expense to invoice
@login_required(login_url='login/')
def add_invoice_expense(request, invoice_id):
	invoice = get_object_or_404(Invoice, pk=invoice_id)
	try:
		e = invoice.expense_set.create(description=request.POST['description'], cost=request.POST['cost'], qty=request.POST['qty'])
		e.save()
	except (KeyError, Invoice.DoesNotExist):
		return render(request, 'view_invoice.html', {
			'invoice': invoice,
			'error_message': 'Not all fields were completed.',
		})
	else:
		return HttpResponseRedirect(reverse('drycleaners:invoice', args=(invoice.id,)))



# Delete expense from invoice
@login_required(login_url='login/')
def delete_invoice_expense(request, expense_id, invoice_id):
	expense = get_object_or_404(Expense, pk=expense_id)
	invoice = get_object_or_404(Invoice, pk=invoice_id)
	try:
		expense.delete()
	except (KeyError, Expense.DoesNotExist):
		return render(request, 'view_invoice.html', {
			'invoice': invoice,
			'error_message': 'Expense does not exist.',
		})
	else:
		return HttpResponseRedirect(reverse('drycleaners:invoice', args=(invoice.id,)))

		

# List all business expenses (expense item with no invoice_id)
@login_required(login_url='login/')
def expense_list(request):
	expenses = Expense.objects.filter(invoice_id=None)
	context = {
		'expenses' : expenses,
	}
	return render(request, 'expenses.html', context)


		
# New business expense
@login_required(login_url='login/')
def new_business_expense(request):
	if request.method == 'POST':
		# Stuff from form
		date = datetime.datetime.strptime(request.POST['date'], "%m/%d/%Y")
		e = Expense(description=request.POST['description'], date=date, cost=request.POST['cost'], qty=request.POST['qty'])
		e.save()
		return HttpResponseRedirect(reverse('drycleaners:expense_list'))
	else:
		return render(request, 'new_expense.html')
		
		
		
# Upload attachment for business expense
@login_required(login_url='login/')
def upload_business_expense_attachment(request, expense_id):
    # Get expense
    expense = get_object_or_404(Expense, pk=expense_id)
    
    if request.method == 'POST':
        # Get file from POST data
        myfile = request.FILES['file']
        
        # Save file to filesystem
        fs = FileSystemStorage()
        fs.save(myfile.name, myfile)
        
        # Create new ExpenseAttachment record
        e = expense.expenseattachment_set.create(file=myfile, displayname=myfile.name)
        e.save()
        
		# Redirect to expenses list
        return HttpResponseRedirect(reverse('drycleaners:expense_list'))
    else:
        context = {
            'expense' : expense,
        }
        return render(request, 'upload_attachment.html', context)
	
	
	
# Delete attachment from business expense
@login_required(login_url='login/')
def delete_business_expense_attachment(request, expense_id, expenseattachment_id):
	expense = get_object_or_404(Expense, pk=expense_id)
	expenseattachment = get_object_or_404(ExpenseAttachment, pk=expenseattachment_id)
	try:
		expenseattachment.delete()
		fs = FileSystemStorage()
		fs.delete(expenseattachment)
	except:
		context = {
			'error_message' : "Unable to delete attachment!",
		}
		return render(request, 'expenses.html', context)
	else:
		return HttpResponseRedirect(reverse('drycleaners:expense_list'))

		

# Delete business expense
@login_required(login_url='login/')
def delete_business_expense(request, expense_id):
	expense = get_object_or_404(Expense, pk=expense_id)
	try:
		expense.delete()
	except (KeyError, Expense.DoesNotExist):
		return render(request, 'expenses.html', {
			'error_message': 'Expense does not exist!',
		})
	else:
		return HttpResponseRedirect(reverse('drycleaners:expense_list'))	

drycleaners/views/items.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.contrib.auth.decorators import login_required

from drycleaners.models import Customer, Invoice, InvoiceItem, Expense, InvoiceAttachment, ExpenseAttachment



# Add invoiceitem to invoice
@login_required(login_url='login/')
def add_item(request, invoice_id):
	invoice = get_object_or_404(Invoice, pk=invoice_id)
	try:
		i = invoice.invoiceitem_set.create(name=request.POST['name'], description=request.POST['description'], cost=request.POST['cost'], qty=request.POST['qty'])
		i.save()
	except (KeyError, Invoice.DoesNotExist):
		return render(request, 'view_invoice.html', {
			'invoice': invoice,
			'error_message': 'Not all fields were completed.',
		})
	else:
		return HttpResponseRedirect(reverse('drycleaners:invoice', args=(invoice.id,)))



# Delete invoiceitem from invoice
@login_required(login_url='login/')
def delete_item(request, invoiceitem_id, invoice_id):
	
	item = get_object_or_404(InvoiceItem, pk=invoiceitem_id)
	invoice = get_object_or_404(Invoice, pk=invoice_id)
	try:
		item.delete()
	except (KeyError, InvoiceItem.DoesNotExist):
		return render(request, 'view_invoice.html', {
			'invoice': invoice,
			'error_message': 'Item does not exist.',
		})
	else:
		return HttpResponseRedirect(reverse('drycleaners:invoice', args=(invoice.id,)))

drycleaners/views/reports.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.core.files.storage import FileSystemStorage
from django.contrib.auth.decorators import login_required
from itertools import chain
import datetime

from drycleaners.models import Customer, Invoice, InvoiceItem, Expense, InvoiceAttachment, ExpenseAttachment	



# Accounting report
@login_required(login_url='login/')
def accounting(request):
	if request.method == 'POST':
		start = datetime.datetime.strptime(request.POST['start'], "%m/%d/%Y")
		end = datetime.datetime.strptime(request.POST['end'], "%m/%d/%Y")
		
		if start > end:
			context = {
				'error_message' : "Start date must be before end date!",
			}
			return render(request, 'accounting.html', context)
		else:
			paidinvoices = Invoice.objects.filter(date__gt=start).filter(date__lt=end).filter(status = 'Paid')
			allinvoices = Invoice.objects.filter(date__gt=start).filter(date__lt=end)
			expenses = Expense.objects.filter(date__gt=start).filter(date__lt=end)
			
			# Sum of all paid invoices
			invoicetotal = 0
			for i in paidinvoices:
				invoicetotal += i.total_items()
				
			# Add invoice expenses within date range, regardless of invoice status
			for i in allinvoices:
				expenses = list(chain(expenses, Expense.objects.filter(invoice=i)))
			
			# Sum of all expenses
			expensetotal = 0
			for expense in expenses:
				expensetotal += expense.total()
			
			context = {
				'start' : start,
				'end' : end,
				'invoices' : paidinvoices,
				'expenses' : expenses,
				'invoicetotal' : invoicetotal,
				'expensetotal' : expensetotal,
				'nettotal' : invoicetotal - expensetotal,
			}
			return render(request, 'accounting.html', context)
	else:
		return render(request, 'accounting.html')

drycleaners/templates/base.html
{% load static %}
<!DOCTYPE HTML>
<html lang="en">

<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">

	{% if title %}
	<title>{{ title }}</title>
	{% else %}
	<title>Dry Cleaners</title>
	{% endif %}	
	
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
	<script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
	<script src="{% static 'bootstrap-datepicker/js/bootstrap-datepicker.min.js' %}"></script>
	
	<link rel="stylesheet" type="text/css" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'bootstrap/css/bootstrap-theme.min.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'bootstrap-datepicker/css/bootstrap-datepicker.min.css' %}">
</head>

<body>
	<nav class="navbar navbar-inverse navbar-static-top">
		<div class="container">
			<div class="navbar-header">
				<a class="navbar-brand" href="{% url 'drycleaners:index' %}"><strong>dry</strong>cleaners</a>
			</div>
			
			{% if user.is_authenticated %}
			
			<div class="collapse navbar-collapse">
				<ul class="nav navbar-nav">
					<li class="dropdown">
						<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button">Invoices <span class="caret"></span></a>
						<ul class="dropdown-menu">
							<li><a href="{% url 'drycleaners:new_invoice' %}"><strong>New Invoice</strong></a></li>
							<li><a href="{% url 'drycleaners:index' %}">Recent</a></li>
							<li class="divider" role="separator"></li>
							<li><a href="{% url 'drycleaners:all_invoices' %}">List All</a></li>
							<li><a href="{% url 'drycleaners:draft_invoices' %}">Draft Invoices</a></li>
							<li><a href="{% url 'drycleaners:paid_invoices' %}">Paid Invoices</a></li>
							<li><a href="{% url 'drycleaners:unpaid_invoices' %}">Unpaid Invoices</a></li>
						</ul>
					</li>
					<li class="dropdown">
						<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button">Customers <span class="caret"></span></a>
						<ul class="dropdown-menu">
							<li><a href="{% url 'drycleaners:new_customer' %}"><strong>New Customer</strong></a></li>
							<li role="separator" class="divider"></li>
							<li><a href="{% url 'drycleaners:customer_list' %}">List All</a></li>
						</ul>
					</li>
					<li class="dropdown">
						<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button">Expenses <span class="caret"></span></a>
						<ul class="dropdown-menu">
							<li><a href="{% url 'drycleaners:new_business_expense' %}"><strong>New Expense</strong></a></li>
							<li role="separator" class="divider"></li>
							<li><a href="{% url 'drycleaners:expense_list' %}">List All</a></li>
						</ul>
					</li>
					<li class="dropdown">
						<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button">Reports <span class="caret"></span></a>
						<ul class="dropdown-menu">
							<li><a href="{% url 'drycleaners:accounting' %}">Accounting</a></li>
						</ul>
					</li>
					<li class="dropdown">
						<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button">Admin <span class="caret"></span></a>
						<ul class="dropdown-menu">
							<li><a href="{% url 'drycleaners:users' %}">Users</a></li>
							<li><a href="{% url 'drycleaners:settings' %}">Settings</a></li>
						</ul>
					</li>
				</ul>
				
				<form class="navbar-form navbar-right" action="{% url 'drycleaners:search_invoice' %}" method="POST">
					{% csrf_token %}
					<div class="form-group">
						<input type="text" class="form-control" placeholder="Invoice Number" name="id">
					</div>
					<button type="submit" class="btn btn-default">Go</button>
				</form>
				
				<ul class="nav navbar-nav navbar-right">
					<li class="dropdown">
						<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button">Hello, {{ user.username }}</a>
						<ul class="dropdown-menu">
							<li><a href="{% url 'drycleaners:logout' %}">Logout</a></li>
						</ul>
					</li>
				</ul>
			</div>
			
			{% endif %}
			
		</div>
	</nav>
	
	<div class="container">

{% block content %}

{% endblock %}

	</div>
</body>

</html>

drycleaners/templates/customer.html
{% extends 'base.html' %}

{% block content %}

{% if error_message %}
<div class="danger">{{ error_message }}</div>
{% endif %}

{% if customer %}

<h2 class="text-center">{{ customer.name }}</h2>

<!-- Customer information -->

<form method="POST" action="{% url 'drycleaners:update_customer' customer.id %}" name="customer" class="form-horizontal">
	{% csrf_token %}
	<div class="panel panel-primary">
		<div class="panel-heading">Customer Info</div>
		<div class="panel-body">
			<div class="form-group">
				<label class="col-sm-3 control-label">ID:</label>
				<div class="col-sm-6">
					<p class="form-control-static">{{ customer.id }}</a></p>
				</div>
			</div>
			<div class="form-group">
				<label class="col-sm-3 control-label">Name:</label>
				<div class="col-sm-6">
					<input type="text" class="form-control" name="name" value="{{ customer.name }}" />
				</div>
			</div>
			<div class="form-group">
				<label class="col-sm-3 control-label">Address 1:</label>
				<div class="col-sm-6">
					<input type="text" class="form-control" name="address1" value="{{ customer.address1 }}" />
				</div>
			</div>
			<div class="form-group">
				<label class="col-sm-3 control-label">Address 2:</label>
				<div class="col-sm-6">
					<input type="text" class="form-control" name="address2" value="{{ customer.address2 }}" />
				</div>
			</div>
			<div class="form-group">
				<label class="col-sm-3 control-label">City State Zip:</label>
				<div class="col-sm-3">
					<input type="text" class="form-control" name="city" value="{{ customer.city }}" />
				</div>
				<div class="col-sm-1">
					<input type="text" class="form-control" name="state" value="{{ customer.state }}" />
				</div>
				<div class="col-sm-2">
					<input type="text" class="form-control" name="zip" value="{{ customer.zip }}" />
				</div>
			</div>
			<div class="form-group">
				<label class="col-sm-3 control-label">Email:</label>
				<div class="col-sm-4">
					<input type="text" class="form-control" name="email" value="{{ customer.email }}" />
				</div>
				<div class="col-sm-2">
					<a href="mailto:{{ customer.email }}" class="btn btn-default form-control">Send E-mail</a>
				</div>
			</div>
		</div>
		<div class="panel-footer">
			<input type="submit" value="Update" class="btn btn-primary">
		</div>
	</div>
</form>

<!-- END Customer information -->

<!-- Customer invoices -->

<div class="panel panel-primary">
	<div class="panel-heading">Customer Invoices</div>
	<table class="table table-hover">
		<tr>
			<th>Invoice</th>
			<th>Date</th>
			<th>Status</th>
			<th>Total</th>
			<th class="text-right">Actions</th>
		</tr>
	{% for invoice in invoices %}
		<tr>
			<td>{{ invoice.id }}</td>
			<td>{{ invoice.date }}</td>
			<td>{{ invoice.status }}</td>
			<td>{{ invoice.total_items }}</td>
			<td class="text-right">
				<a href="{% url 'drycleaners:invoice' invoice.id %}" class="btn btn-xs btn-primary">View</a>
				<button type="button" data-toggle="modal" data-target="#confirmdelete" data-object-name="{{ invoice.id }}" data-delete-url="{% url 'drycleaners:delete_invoice' invoice.id %}" class="btn btn-xs btn-danger">Delete</button>
			</td>
		</tr>
	{% endfor %}
	</table>
</div>

<!-- Delete confirmation modal -->
<div class="modal fade" id="confirmdelete" role="dialog">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<h4 class="modal-title">Confirm</h4>
			</div>
			<div class="modal-body">
				
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-default" data-dismiss="modal">No</button>
				<a href="#" class="btn btn-danger">Yes</a>
			</div>
		</div>
	</div>
</div>

<script>
	$(document).ready(function() {
		$('#confirmdelete').on('show.bs.modal', function(e) {
			var name = $(e.relatedTarget).data('object-name');
			var url = $(e.relatedTarget).data('delete-url');
			$('#confirmdelete .modal-body').html("Are you sure you want to delete invoice " + name + "?<br><i>This will delete all associated items, expenses, and attachments!</i>");
			$('#confirmdelete .modal-footer a').attr('href', url);
		});
	});
</script>
<!-- END delete confirmation modal -->

{% endif %}

{% endblock %}

drycleaners/templates/new_invoice.html
{% extends 'base.html' %}

{% block content %}

{% if error_message %}
<div class="alert alert-danger">{{ error_message }}</div>
{% endif %}

{% if customer_list %}

<form method="POST" action="{% url 'drycleaners:new_invoice' %}" name="customer" class="form-horizontal">
	{% csrf_token %}
	<div class="panel panel-primary">
		<div class="panel-heading">Select Customer</div>
		<div class="panel-body">
			<div class="form-group">
				<label class="col-sm-3 control-label">Customer:</label>
				<div class="col-sm-6">
					<select class="form-control" name="customer_id">
						<option value="None">(Select)</option>
						{% for customer in customer_list %}
						<option value="{{ customer.id }}">{{ customer.name }}</option>
						{% endfor %}
					</select>
				</div>
			</div>
		</div>
		<div class="panel-footer">
			<a href="{% url 'drycleaners:new_customer' %}" class="btn btn-default">Add New Customer</a>
			<input type="submit" value="Create Invoice" class="btn btn-primary">
		</div>
	</div>
</form>

{% else %}

<div class="alert alert-danger">No customers!</div>

{% endif %}

{% endblock %}